name: Build
on:
    pull_request:
    push:
      branches: [main]
      tags: [v*]
jobs:
  build:
    runs-on: [ubuntu-latest] 
    steps:
      - uses: AlchemyViewer/action-autobuild@v5
        with:
          platform: common
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: AlchemyViewer/action-autobuild-release@v4
        with:
          public: true
